variable "prefix" {}
variable "env" {}
variable "location" {}
variable "resource_group_name" {}
variable "web_subnet_id" {}
variable "vm_size" {}
variable "vm_admin_username" {}
variable "vm_admin_password" {}
variable "source_image_id" {}
variable "managed_id_reader" {}
