variable "prefix" {}
variable "env" {}
variable "location" {}
variable "resource_group_name" {}
variable "web_subnet_id" {}
variable "appgw_managed_id" {}
variable "app_selfcert_name" {}
variable "app_selfcert_versionless_secret_id" {}
variable "dns_zone_name" {}
