variable "prefix" {}
variable "env" {}
variable "location" {}
variable "resource_group_name" {}
variable "webappcontainer_managed_id" {}
variable "webappcontainer_client_id" {}
variable "vault_name" {}
variable "secret_key_base_uri" {}
variable "docker_image_name" {}
variable "docker_image_tag" {}
